/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * delete_rec.java
 *
 * Created on Sep 21, 2014, 5:02:58 PM
 */
package main_project;

import com.mongodb.MongoException;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NIRAJ
 */
public class delete_rec extends javax.swing.JFrame {

    /** Creates new form delete_rec */
    public delete_rec() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Delete_rec = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        Reg_No = new javax.swing.JLabel();
        Reg_No_Text = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Delete_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        Delete_rec.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30));
        Delete_rec.setText("Delete Record");
        getContentPane().add(Delete_rec);
        Delete_rec.setBounds(390, 10, 220, 70);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18));
        Menu.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\images (11).jpg")); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(921, 18, 70, 69);

        Reg_No.setFont(new java.awt.Font("Tahoma", 1, 16));
        Reg_No.setText("Registration No:");
        getContentPane().add(Reg_No);
        Reg_No.setBounds(270, 190, 160, 20);

        Reg_No_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        Reg_No_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_No_TextActionPerformed(evt);
            }
        });
        getContentPane().add(Reg_No_Text);
        Reg_No_Text.setBounds(440, 190, 148, 25);

        Delete.setBackground(new java.awt.Color(255, 255, 255));
        Delete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        Delete.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\del.jpg")); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(620, 170, 50, 50);

        Delete_Table.setFont(new java.awt.Font("Tahoma", 0, 14));
        Delete_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg. No", "First Name", "Last Name", "Roll No", "Dept", "Class", "Address", "Mobile", "DOB", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Delete_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Delete_Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 300, 991, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\textures_1920x1080_wallpaper_Wallpaper_1920x1080_www.wallpaperswa.com.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

DefaultTableModel u = (DefaultTableModel) Delete_Table.getModel();
int no = u.getRowCount();
int n=0;
for(n=0; n<no; n++)
    {
     u.removeRow(0);   
    }
    String Reg_No_1;
    Reg_No_1 = Reg_No_Text.getText();
    if (Reg_No_1.equals("") || !Pattern.matches("[0-9]+", Reg_No_1) ){
    JOptionPane.showMessageDialog(null, "Please Enter Valid Registration Number");
}
    else {
    try {
            Mongo mongo=new Mongo("127.0.0.1",27017);
            DB db= mongo.getDB("Project_Demo");
            DBCollection collection=db.getCollection("Registration");
            DBCollection collection1=db.getCollection("Attendance");
            DBCollection collection2=db.getCollection("Marks");
            DBCollection collection3=db.getCollection("Fees");
            BasicDBObject query = new BasicDBObject();
            query.put("Reg_No",Reg_No_1);
            DBCursor cursor = collection.find(query);
              DBCursor cursor1 = collection1.find(query);
                DBCursor cursor2 = collection2.find(query);
                  DBCursor cursor3 = collection3.find(query);
            try{
                if(cursor.hasNext() || cursor1.hasNext() || cursor2.hasNext()|| cursor3.hasNext()){
                        u.addRow(new Object[]{cursor.next().get("Reg_No"),cursor.curr().get("Fname"),cursor.curr().get("Lname")
                                ,cursor.curr().get("Roll_No"),cursor.curr().get("Dept"),cursor.curr().get("Class")
                                ,cursor.curr().get("Address"),cursor.curr().get("Mobile"),cursor.curr().get("DOB")
                                ,cursor.curr().get("Email")/*,cursor1.curr().get("Attendance"),cursor2.curr().get("Ten'th"),
                        cursor2.curr().get("Twelve"),cursor2.curr().get("FE"),cursor2.curr().get("SE"),
                        cursor2.curr().get("TE"),cursor2.curr().get("BE")*/});
                         collection.remove(query);
                         collection1.remove(query);
                         collection2.remove(query);
                         collection3.remove(query);
                         JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
                        }
                else {
                     JOptionPane.showMessageDialog(null, "Record is Not Found");
                }
               
            }
            finally{
                cursor.close();
            }
                    
    }
    catch (UnknownHostException ex) {
            Logger.getLogger(add_marks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MongoException ex) {
            Logger.getLogger(add_marks.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }         
}//GEN-LAST:event_DeleteActionPerformed

private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new menu().setVisible(true);
}//GEN-LAST:event_MenuActionPerformed

private void Reg_No_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_No_TextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Reg_No_TextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_rec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_rec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_rec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_rec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new delete_rec().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Delete;
    private javax.swing.JTable Delete_Table;
    private javax.swing.JLabel Delete_rec;
    private javax.swing.JButton Menu;
    private javax.swing.JLabel Reg_No;
    private javax.swing.JTextField Reg_No_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
