/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on Sep 21, 2014, 3:11:59 PM
 */
package main_project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author NIRAJ
 */
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        U_Name = new javax.swing.JLabel();
        U_Name_Text = new javax.swing.JTextField();
        U_Pass = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        U_Pass_Text = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1125, 610));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        U_Name.setFont(new java.awt.Font("Kristen ITC", 1, 14));
        U_Name.setForeground(new java.awt.Color(255, 255, 255));
        U_Name.setText("User Name:");
        jPanel1.add(U_Name);
        U_Name.setBounds(20, 30, 100, 20);

        U_Name_Text.setFont(new java.awt.Font("Tahoma", 0, 14));
        U_Name_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_Name_TextActionPerformed(evt);
            }
        });
        U_Name_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                U_Name_TextKeyPressed(evt);
            }
        });
        jPanel1.add(U_Name_Text);
        U_Name_Text.setBounds(150, 30, 237, 29);

        U_Pass.setFont(new java.awt.Font("Kristen ITC", 1, 14));
        U_Pass.setForeground(new java.awt.Color(255, 255, 255));
        U_Pass.setText("Password:");
        jPanel1.add(U_Pass);
        U_Pass.setBounds(30, 80, 90, 20);

        Login.setBackground(new java.awt.Color(0, 51, 51));
        Login.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Log In");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(90, 130, 100, 30);

        Clear.setBackground(new java.awt.Color(0, 51, 51));
        Clear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16));
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(250, 130, 100, 30);

        U_Pass_Text.setFont(new java.awt.Font("Tahoma", 0, 14));
        U_Pass_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                U_Pass_TextKeyPressed(evt);
            }
        });
        jPanel1.add(U_Pass_Text);
        U_Pass_Text.setBounds(150, 80, 237, 27);

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\1.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 440, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 200, 440, 190);

        welcome.setBackground(new java.awt.Color(204, 204, 255));
        welcome.setFont(new java.awt.Font("Pristina", 0, 55));
        welcome.setForeground(new java.awt.Color(79, 0, 0));
        welcome.setText("Welcome");
        getContentPane().add(welcome);
        welcome.setBounds(410, 130, 225, 67);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 34));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\VIT main logo.png")); // NOI18N
        jLabel1.setText("Vishwakarma Institute of Information Technology, Pune ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1106, 126);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(13, 25, 0, 0);

        Exit.setBackground(new java.awt.Color(0, 51, 51));
        Exit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(790, 440, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\abstract-blue_00428188 - Copy.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1110, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_ExitActionPerformed

private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
// TODO add your handling code here:
    U_Name_Text.setText("");
    U_Pass_Text.setText("");
}//GEN-LAST:event_ClearActionPerformed

private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
String Name,Pass;
Name = U_Name_Text.getText();
Pass = U_Pass_Text.getText();
if (Name.equals("")){
    JOptionPane.showMessageDialog(null,"Please Enter User Name..!!");
}
else if (!Name.equals("Admin")){
    JOptionPane.showMessageDialog(null,"Please Enter Correct User Name..!!");
}
else if (Pass.equals("")){
    JOptionPane.showMessageDialog(null,"Please Enter Password..!!");
}

else if (!Pass.equals("Password")){
    JOptionPane.showMessageDialog(null,"Please Enter Correct Password..!!");
}
else {
    this.setVisible(false);
    new menu().setVisible(true);
    }
}//GEN-LAST:event_LoginActionPerformed

private void U_Name_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_U_Name_TextKeyPressed
if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
    JOptionPane.showMessageDialog(null,"Please Enter only charecters..!!");
   U_Name_Text.setText("");
}
}//GEN-LAST:event_U_Name_TextKeyPressed

private void U_Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_Name_TextActionPerformed

}//GEN-LAST:event_U_Name_TextActionPerformed

private void U_Pass_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_U_Pass_TextKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    String Name,Pass;

Name = U_Name_Text.getText();
Pass = U_Pass_Text.getText();
if (Name.equals("")){
    JOptionPane.showMessageDialog(null,"Please Enter User Name..!!");
}
else if (!Name.equals("Admin")){
    JOptionPane.showMessageDialog(null,"Please Enter Correct User Name..!!");
}
else if (Pass.equals("")){
    JOptionPane.showMessageDialog(null,"Please Enter Password..!!");
}

else if (!Pass.equals("Password")){
    JOptionPane.showMessageDialog(null,"Please Enter Correct Password..!!");
}
else {
    this.setVisible(false);
    new menu().setVisible(true);
    
    
   
}
}
}//GEN-LAST:event_U_Pass_TextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JLabel U_Name;
    private javax.swing.JTextField U_Name_Text;
    private javax.swing.JLabel U_Pass;
    private javax.swing.JPasswordField U_Pass_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
