/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menu.java
 *
 * Created on Sep 21, 2014, 3:31:32 PM
 */
package main_project;


/**
 *
 * @author NIRAJ
 */
public class menu extends javax.swing.JFrame {


    /** Creates new form menu */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        log_out = new javax.swing.JButton();
        new_rec = new javax.swing.JButton();
        delete_rec = new javax.swing.JButton();
        student_details = new javax.swing.JButton();
        search_rec = new javax.swing.JButton();
        update_rec = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        log_out.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        log_out.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\25701919-logout-icon-or-user-or-member-logout-button-or-banner.jpg")); // NOI18N
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        jPanel2.add(log_out);
        log_out.setBounds(700, 230, 80, 79);

        new_rec.setBackground(new java.awt.Color(255, 255, 255));
        new_rec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        new_rec.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\file_add.png")); // NOI18N
        new_rec.setText("Add New Record");
        new_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_recActionPerformed(evt);
            }
        });
        jPanel2.add(new_rec);
        new_rec.setBounds(280, 100, 240, 50);

        delete_rec.setBackground(new java.awt.Color(255, 255, 255));
        delete_rec.setFont(new java.awt.Font("Tahoma", 0, 14));
        delete_rec.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\del.jpg")); // NOI18N
        delete_rec.setText("  Delete Record ");
        delete_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_recActionPerformed(evt);
            }
        });
        jPanel2.add(delete_rec);
        delete_rec.setBounds(280, 310, 240, 50);

        student_details.setBackground(new java.awt.Color(255, 255, 255));
        student_details.setFont(new java.awt.Font("Tahoma", 0, 14));
        student_details.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\Photobooth-icon - Copy.png")); // NOI18N
        student_details.setText("Student Details");
        student_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_detailsActionPerformed(evt);
            }
        });
        jPanel2.add(student_details);
        student_details.setBounds(280, 170, 240, 50);

        search_rec.setBackground(new java.awt.Color(255, 255, 255));
        search_rec.setFont(new java.awt.Font("Tahoma", 0, 14));
        search_rec.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\Preview-2-icon.png")); // NOI18N
        search_rec.setText("Search Record");
        search_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_recActionPerformed(evt);
            }
        });
        jPanel2.add(search_rec);
        search_rec.setBounds(280, 380, 240, 49);

        update_rec.setBackground(new java.awt.Color(255, 255, 255));
        update_rec.setFont(new java.awt.Font("Tahoma", 0, 14));
        update_rec.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\update.jpg")); // NOI18N
        update_rec.setText("Update Record");
        update_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_recActionPerformed(evt);
            }
        });
        jPanel2.add(update_rec);
        update_rec.setBounds(280, 240, 240, 50);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 36));
        jLabel2.setText("Student Information System");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 40, 450, 60);
        jPanel2.add(clock);
        clock.setBounds(660, 4, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\project\\er\\er\\665310936.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void student_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_detailsActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new student_details().setVisible(true);
    
}//GEN-LAST:event_student_detailsActionPerformed

private void new_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_recActionPerformed
           
      this.setVisible(false);     
      new Registration_Form().setVisible(true);  
   
}//GEN-LAST:event_new_recActionPerformed

private void delete_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_recActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new delete_rec().setVisible(true);
}//GEN-LAST:event_delete_recActionPerformed

private void update_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_recActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new update().setVisible(true);
}//GEN-LAST:event_update_recActionPerformed

private void search_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_recActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new search().setVisible(true);
}//GEN-LAST:event_search_recActionPerformed

private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new LogIn().setVisible(true);
}//GEN-LAST:event_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new menu().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JButton delete_rec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton log_out;
    private javax.swing.JButton new_rec;
    private javax.swing.JButton search_rec;
    private javax.swing.JButton student_details;
    private javax.swing.JButton update_rec;
    // End of variables declaration//GEN-END:variables
}
