/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * search.java
 *
 * Created on Sep 21, 2014, 5:31:25 PM
 */
package main_project;
import com.mongodb.MongoException;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NIRAJ
 */
public class search extends javax.swing.JFrame {

    /** Creates new form search */
    public search() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_rec = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Reg_No = new javax.swing.JLabel();
        Reg_No_Text = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Search_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 550));
        getContentPane().setLayout(null);

        Search_rec.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36));
        Search_rec.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\images (1).jpg")); // NOI18N
        Search_rec.setText("Search Record");
        getContentPane().add(Search_rec);
        Search_rec.setBounds(300, 10, 340, 60);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18));
        Menu.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\images (11).jpg")); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(990, 20, 70, 70);

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        Clear.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\images (2).jpg")); // NOI18N
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(926, 322, 120, 45);

        Reg_No.setFont(new java.awt.Font("Tahoma", 0, 16));
        Reg_No.setText("Registration No:");
        getContentPane().add(Reg_No);
        Reg_No.setBounds(340, 170, 115, 20);

        Reg_No_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(Reg_No_Text);
        Reg_No_Text.setBounds(480, 170, 145, 25);

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        Search.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\Preview-2-icon.png")); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(650, 160, 50, 40);

        Search_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg No.", "First Name", "Last Name", "Roll No", "Dept", "Class", "Address", "Mobile", "DOB", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Search_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Search_Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 1070, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\textures_1920x1080_wallpaper_Wallpaper_1920x1080_www.wallpaperswa.com.jpg")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(952, 650));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new menu().setVisible(true);
}//GEN-LAST:event_MenuActionPerformed

private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

    
DefaultTableModel u = (DefaultTableModel) Search_Table.getModel();
int no = u.getRowCount();
int n=0;
for(n=0; n<no; n++)
    {
     u.removeRow(0);   
    }
    String Reg_No_1;
    Reg_No_1 = Reg_No_Text.getText();
    if (Reg_No_1.equals("") || !Pattern.matches("[0-9]+", Reg_No_1) ){
    JOptionPane.showMessageDialog(null, "Please Enter Valid Registration Number");
}
    else {
    try {
            Mongo mongo=new Mongo("127.0.0.1",27017);
            DB db= mongo.getDB("Project_Demo");
            DBCollection collection=db.getCollection("Registration");
            System.out.println("Connected to DB");
            
            BasicDBObject query = new BasicDBObject();
            query.put("Reg_No",Reg_No_1);
            DBCursor cursor = collection.find(query);
            try{
                while(cursor.hasNext()){
                        u.addRow(new Object[]{cursor.next().get("Reg_No"),cursor.curr().get("Fname"),cursor.curr().get("Lname")
                                ,cursor.curr().get("Roll_No"),cursor.curr().get("Dept"),cursor.curr().get("Class")
                                ,cursor.curr().get("Address"),cursor.curr().get("Mobile"),cursor.curr().get("DOB")
                                ,cursor.curr().get("Email")});
                        

                       
                }
                
            }
            finally{
                cursor.close();
            }
                    
    }
    catch (UnknownHostException ex) {
            Logger.getLogger(add_marks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MongoException ex) {
            Logger.getLogger(add_marks.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }         
}//GEN-LAST:event_SearchActionPerformed

private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
// TODO add your handling code here:
     DefaultTableModel u = (DefaultTableModel) Search_Table.getModel();
int no = u.getRowCount();
int n=0;
for(n=0; n<no; n++)
    {
     u.removeRow(0);   
    }
}//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Menu;
    private javax.swing.JLabel Reg_No;
    private javax.swing.JTextField Reg_No_Text;
    private javax.swing.JButton Search;
    private javax.swing.JTable Search_Table;
    private javax.swing.JLabel Search_rec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
