/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update_Form.java
 *
 * Created on Sep 26, 2014, 6:34:01 PM
 */
package main_project;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NIRAJ
 */
public class Update_Form extends javax.swing.JFrame {
   String Str1,Str2,Str3,Str4,Str6,Str7,Str8,Str5,Str9,Str10;
    public Update_Form() {
         initComponents();
         
         this.setLocationRelativeTo(null);
         }
public Update_Form(String Reg_No_1,String fname,String lname,String roll,String dept,String clas,String adds,
        String mobile,String email,String dob) {
         Str1 = Reg_No_1;
         Str2 = fname;
         Str3 = lname;
         Str4 = roll;
         Str5 = dept;
         Str7 = adds;
         Str8 = mobile;
         Str9 = email;
         Str6 = clas;
         Str10 = dob;
        initComponents();
         }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Reg_No = new javax.swing.JLabel();
        Reg_No_Text = new javax.swing.JTextField();
        Fname_Text = new javax.swing.JTextField();
        Roll_No = new javax.swing.JLabel();
        Dept = new javax.swing.JLabel();
        Dept_List = new javax.swing.JComboBox();
        Class = new javax.swing.JLabel();
        Class_List = new javax.swing.JComboBox();
        Address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address_Text = new javax.swing.JTextArea();
        Mobile = new javax.swing.JLabel();
        Mobile_Text = new javax.swing.JTextField();
        Birth_Date = new javax.swing.JLabel();
        E_Mail = new javax.swing.JLabel();
        E_Mail_Text = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Lname_Text = new javax.swing.JTextField();
        Roll_No_Text = new javax.swing.JTextField();
        Dob_Text = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        stud_profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        Name.setFont(new java.awt.Font("Tahoma", 0, 16));
        Name.setText("Name:");
        jPanel1.add(Name);
        Name.setBounds(30, 67, 47, 20);

        Reg_No.setFont(new java.awt.Font("Tahoma", 0, 16));
        Reg_No.setText("Registration No:");
        jPanel1.add(Reg_No);
        Reg_No.setBounds(30, 18, 115, 20);

        Reg_No_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        Reg_No_Text.setEnabled(false);
        Reg_No_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_No_TextActionPerformed(evt);
            }
        });
        jPanel1.add(Reg_No_Text);
        Reg_No_Text.setBounds(163, 13, 128, 31);

        Fname_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        Fname_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fname_TextActionPerformed(evt);
            }
        });
        jPanel1.add(Fname_Text);
        Fname_Text.setBounds(163, 62, 128, 32);

        Roll_No.setFont(new java.awt.Font("Tahoma", 0, 16));
        Roll_No.setText("Roll No:");
        jPanel1.add(Roll_No);
        Roll_No.setBounds(30, 117, 58, 20);

        Dept.setFont(new java.awt.Font("Tahoma", 0, 16));
        Dept.setText("Department:");
        jPanel1.add(Dept);
        Dept.setBounds(30, 162, 89, 20);

        Dept_List.setFont(new java.awt.Font("Tahoma", 0, 12));
        Dept_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IT", "Computer", "E & TC", "Mechanical", "Civil" }));
        Dept_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dept_ListActionPerformed(evt);
            }
        });
        jPanel1.add(Dept_List);
        Dept_List.setBounds(163, 164, 84, 21);

        Class.setFont(new java.awt.Font("Tahoma", 0, 16));
        Class.setText("Class:");
        jPanel1.add(Class);
        Class.setBounds(30, 202, 42, 20);

        Class_List.setFont(new java.awt.Font("Tahoma", 0, 12));
        Class_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FE", "SE", "TE", "BE" }));
        jPanel1.add(Class_List);
        Class_List.setBounds(163, 204, 77, 21);

        Address.setFont(new java.awt.Font("Tahoma", 0, 16));
        Address.setText("Address:");
        jPanel1.add(Address);
        Address.setBounds(30, 242, 63, 20);

        Address_Text.setColumns(20);
        Address_Text.setRows(5);
        jScrollPane1.setViewportView(Address_Text);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(163, 242, 275, 53);

        Mobile.setFont(new java.awt.Font("Tahoma", 0, 16));
        Mobile.setText("Mobile:");
        jPanel1.add(Mobile);
        Mobile.setBounds(30, 305, 52, 20);

        Mobile_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        jPanel1.add(Mobile_Text);
        Mobile_Text.setBounds(170, 300, 110, 30);

        Birth_Date.setFont(new java.awt.Font("Tahoma", 0, 16));
        Birth_Date.setText("Birth Date:");
        jPanel1.add(Birth_Date);
        Birth_Date.setBounds(30, 350, 76, 20);

        E_Mail.setFont(new java.awt.Font("Tahoma", 0, 16));
        E_Mail.setText("E-mail:");
        jPanel1.add(E_Mail);
        E_Mail.setBounds(30, 419, 51, 20);

        E_Mail_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        E_Mail_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_Mail_TextActionPerformed(evt);
            }
        });
        E_Mail_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                E_Mail_TextKeyPressed(evt);
            }
        });
        jPanel1.add(E_Mail_Text);
        E_Mail_Text.setBounds(163, 406, 224, 33);

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18));
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\update.jpg")); // NOI18N
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(170, 460, 60, 60);

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\icons-390 - Copy.jpg")); // NOI18N
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(290, 460, 60, 60);

        Lname_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        Lname_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname_TextActionPerformed(evt);
            }
        });
        jPanel1.add(Lname_Text);
        Lname_Text.setBounds(301, 62, 128, 32);

        Roll_No_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        Roll_No_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Roll_No_TextActionPerformed(evt);
            }
        });
        jPanel1.add(Roll_No_Text);
        Roll_No_Text.setBounds(163, 112, 128, 32);

        Dob_Text.setFont(new java.awt.Font("Tahoma", 0, 15));
        jPanel1.add(Dob_Text);
        Dob_Text.setBounds(170, 350, 110, 30);

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\back.png")); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(430, 460, 60, 60);

        stud_profile.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36));
        stud_profile.setForeground(new java.awt.Color(102, 102, 255));
        stud_profile.setIcon(new javax.swing.ImageIcon("G:\\project\\pics\\icon\\icons\\Student-id-icon.png")); // NOI18N
        stud_profile.setText("  Student Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(stud_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stud_profile)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Reg_No_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_No_TextActionPerformed

}//GEN-LAST:event_Reg_No_TextActionPerformed

private void Fname_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fname_TextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Fname_TextActionPerformed

private void Dept_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dept_ListActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Dept_ListActionPerformed

private void E_Mail_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_Mail_TextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_E_Mail_TextActionPerformed

private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String Email_Check = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        String Reg_No_1 = Reg_No_Text.getText();
        String Fname = Fname_Text.getText();
        String Lname = Lname_Text.getText();
        String Roll_No_1 = Roll_No_Text.getText();
        String Email = E_Mail_Text.getText();
        String Mobile_1 = Mobile_Text.getText();
        String Dob = Dob_Text.getText();

        if (Reg_No_1.equals("") || !Pattern.matches("[0-9]+", Reg_No_1)){
            JOptionPane.showMessageDialog(null, "Please Enter Valid Registration Number");
        }
        else if (Fname.equals("") || Pattern.matches("[0-9]+", Fname) || Fname.length()>20){
            JOptionPane.showMessageDialog(null, "Enter Valid First Name");
        }
        else if (Lname.equals("") || Pattern.matches("[0-9]+", Lname) || Lname.length()>20){
            JOptionPane.showMessageDialog(null, "Enter Valid Surname");
        }
        else if (Roll_No_1.equals("") || !Pattern.matches("[0-9]+", Roll_No_1) || Roll_No_1.length()>10){
            JOptionPane.showMessageDialog(null, "Enter Valid Roll Number");
        }
        else if (Mobile_1.equals("") || !Pattern.matches("[0-9]+", Mobile_1) || Mobile_1.length()!=10){
            JOptionPane.showMessageDialog(null, "Enter Valid Mobile Number");
        }
        else if (Email.equals("") || !Email.matches(Email_Check)){
            JOptionPane.showMessageDialog(null, "Enter Valid Email Address");
        }

            else {
                 try {
                  Mongo mongo =new Mongo("127.0.0.1",27017); 
                    DB db=mongo.getDB("Project_Demo");
                    DBCollection collection=db.getCollection("Registration");
                    System.out.println("Connected to DB");
                    BasicDBObject save = new BasicDBObject("Reg_No",Reg_No_1);
                    BasicDBObject newDoc=new BasicDBObject();
                    newDoc.put("Fname",Fname_Text.getText());
                    newDoc.put("Lname",Lname_Text.getText());
                    newDoc.put("Roll_No",Roll_No_Text.getText());
                    newDoc.put("Address",Address_Text.getText());
                    newDoc.put("Mobile",Mobile_Text.getText());
                    newDoc.put("Email",E_Mail_Text.getText());
                    newDoc.put("DOB",Dob_Text.getText());
                    newDoc.put("Class",Class_List.getSelectedItem());
                    newDoc.put("Dept",Dept_List.getSelectedItem());
                    BasicDBObject upDoc=new BasicDBObject();
                    upDoc.put("$set",newDoc);
                    collection.update(save,upDoc,false,true);
                    JOptionPane.showMessageDialog(null, "Record Updated Successfully");
                } 
                 catch (UnknownHostException ex) {
                    Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
                }

               this.setVisible(false);
               new menu().setVisible(true);

        }
}//GEN-LAST:event_SubmitActionPerformed

private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

    Fname_Text.setText("");
    Lname_Text.setText("");
    Roll_No_Text.setText("");
    Address_Text.setText("");
    Mobile_Text.setText("");
    E_Mail_Text.setText("");
    Class_List.setSelectedIndex(0);
    Dept_List.setSelectedIndex(0);
    
}//GEN-LAST:event_ClearActionPerformed

private void Lname_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lname_TextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Lname_TextActionPerformed

private void Roll_No_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Roll_No_TextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Roll_No_TextActionPerformed


private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    Reg_No_Text.setText(Str1);
    Fname_Text.setText(Str2);
    Lname_Text.setText(Str3);
    Roll_No_Text.setText(Str4);
    Address_Text.setText(Str7);
    Mobile_Text.setText(Str8);
    E_Mail_Text.setText(Str9);
    Dept_List.setSelectedItem(Str5);
    Class_List.setSelectedItem(Str6);
    Dob_Text.setText(Str10);
    

}//GEN-LAST:event_formWindowOpened

private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new update().setVisible(true);
}//GEN-LAST:event_BackActionPerformed

private void E_Mail_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_E_Mail_TextKeyPressed
// TODO add your handling code here:
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String Email_Check = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        String Reg_No_1 = Reg_No_Text.getText();
        String Fname = Fname_Text.getText();
        String Lname = Lname_Text.getText();
        String Roll_No_1 = Roll_No_Text.getText();
        String Email = E_Mail_Text.getText();
        String Mobile_1 = Mobile_Text.getText();
        String Dob = Dob_Text.getText();
        
        if (Reg_No_1.equals("") || !Pattern.matches("[0-9]+", Reg_No_1)){
            JOptionPane.showMessageDialog(null, "Please Enter Valid Registration Number");
        }
        else if (Fname.equals("") || Pattern.matches("[0-9]+", Fname) || Fname.length()>20){
            JOptionPane.showMessageDialog(null, "Enter Valid First Name");
        }
        else if (Lname.equals("") || Pattern.matches("[0-9]+", Lname) || Lname.length()>20){
            JOptionPane.showMessageDialog(null, "Enter Valid Surname");
        }
        else if (Roll_No_1.equals("") || !Pattern.matches("[0-9]+", Roll_No_1) || Roll_No_1.length()>10){
            JOptionPane.showMessageDialog(null, "Enter Valid Roll Number");
        }
        else if (Mobile_1.equals("") || !Pattern.matches("[0-9]+", Mobile_1) || Mobile_1.length()!=10){
            JOptionPane.showMessageDialog(null, "Enter Valid Mobile Number");
        }
        else if (Email.equals("") || !Email.matches(Email_Check)){
            JOptionPane.showMessageDialog(null, "Enter Valid Email Address");
        }

            else {
                 try {
                  Mongo mongo =new Mongo("127.0.0.1",27017); 
                    DB db=mongo.getDB("Project_Demo");
                    DBCollection collection=db.getCollection("Registration");
                    System.out.println("Connected to DB");
                    BasicDBObject save = new BasicDBObject("Reg_No",Reg_No_1);
                    BasicDBObject newDoc=new BasicDBObject();
                    newDoc.put("Fname",Fname_Text.getText());
                    newDoc.put("Lname",Lname_Text.getText());
                    newDoc.put("Roll_No",Roll_No_Text.getText());
                    newDoc.put("Address",Address_Text.getText());
                    newDoc.put("Mobile",Mobile_Text.getText());
                    newDoc.put("Email",E_Mail_Text.getText());
                    newDoc.put("DOB",Dob_Text.getText());
                    newDoc.put("Class",Class_List.getSelectedItem());
                    newDoc.put("Dept",Dept_List.getSelectedItem());
                    BasicDBObject upDoc=new BasicDBObject();
                    upDoc.put("$set",newDoc);
                    collection.update(save,upDoc,false,true);
                    JOptionPane.showMessageDialog(null, "Record Updated Successfully");
                } 
                 catch (UnknownHostException ex) {
                    Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
                }

               this.setVisible(false);
               new menu().setVisible(true);

        }
}
}//GEN-LAST:event_E_Mail_TextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Update_Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    public javax.swing.JTextArea Address_Text;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Birth_Date;
    private javax.swing.JLabel Class;
    public javax.swing.JComboBox Class_List;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Dept;
    public javax.swing.JComboBox Dept_List;
    private javax.swing.JTextField Dob_Text;
    private javax.swing.JLabel E_Mail;
    public javax.swing.JTextField E_Mail_Text;
    public javax.swing.JTextField Fname_Text;
    public javax.swing.JTextField Lname_Text;
    private javax.swing.JLabel Mobile;
    public javax.swing.JTextField Mobile_Text;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Reg_No;
    public javax.swing.JTextField Reg_No_Text;
    private javax.swing.JLabel Roll_No;
    public javax.swing.JTextField Roll_No_Text;
    public javax.swing.JButton Submit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel stud_profile;
    // End of variables declaration//GEN-END:variables
}
